Remove irrelevant options from checklist in PULL_REQUEST_TEMPLATE.md …
anitab-org/open-source-programs-web pull request #101
Opened 2021-02-28 07:38 UTC by mehakkkk

…#100

### Description
removed irrelevant option from the PULL_REQUEST_TEMPLATE.md file.

Fixes #100 

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (checklist update on PULL_REQUEST_TEMPLATE.md file)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

**Desktop (please complete the following information):
OS: Linux
Browser: Chrome
Version: Version 86.0.4240.198

2021-02-28 17:10 UTC, Rahulm2310 commented
@mehakkkk Just a request, if you want to work on a issue, please comment on the issue requesting a maintainer to assign you and wait until it is assigned to you. Please be patient. You will get ample chances to contribute.

Cc : @isabelcosta

2021-03-01 05:59 UTC, mehakkkk commented
@Rahulm2310 I apologize for this fretful behaviour. I am new to open source and getting acquainted with it. Will make sure to follow all the guidelines provided.

2021-03-05 09:08 UTC, codesankalp commented
@mehakkkk Please comment on the issue and I will assign it to you.
And next time keep @Rahulm2310 point in mind while contributing to this organization.

2021-03-05 09:09 UTC, codesankalp approved these changes
LGTM @mehakkkk :tada:

2021-03-05 17:36 UTC, Aaishpra commented on .github/PULL_REQUEST_TEMPLATE.md
> +**Desktop (please complete the following information):
No need for desktop and browser details to be included in PR templates, please remove this

2021-03-05 17:38 UTC, Aaishpra requested changes
@mehakkkk can you edit the PR description and remove the "..#100" from the top.

2021-03-05 19:33 UTC, Rahulm2310 commented
@mehakkkk Also, please remove irrelevant options from your PR description (under the checklist and code/quality assurance only).

2021-03-07 20:11 UTC, ashwinijha6 requested changes
@mehakkkk could you please mention the type `fix` in the PR title & remove the line `...#100` before the description

2021-03-07 20:15 UTC, ashwinijha6 requested changes
Also you could add this line in the `Checklist:`
* Update requirements.txt
What do you think @codesankalp

2021-03-07 20:28 UTC, codesankalp commented
@ashwinijha6 There is no `requirements.txt` in this repo but yeah @mehakkkk can add the line for updating `package.json`.

2021-03-07 20:32 UTC, ashwinijha6 commented
> @ashwinijha6 There is no `requirements.txt` in this repo but yeah @mehakkkk can add the line for updating `package.json`.

Oh ya @codesankalp

2021-03-07 20:34 UTC, ashwinijha6 requested changes
Update Docusaurus documentation and the exported file at /docs folder
This could also be added @mehakkkk 
cc : - @codesankalp

2021-03-13 21:00 UTC, codesankalp commented
@mehakkkk Are you going to work on it?
@Aaishpra @keshakaneria Should we close this pull request as there is no response from @mehakkkk?

2021-03-14 08:52 UTC, Aaishpra commented
Yaa i think we should close this Pr and make the issue available for others.

2021-03-14 08:52 UTC, Aaishpra commented
Closing this due to inactivity

2021-03-14 08:52 UTC, closed without merging