fix: Fix profile edit form on submission
anitab-org/open-source-programs-web pull request #119
Opened 2021-03-09 13:48 UTC by ruddi10

### Description

When a user edit or fill the profile even after pressing the submit button the form remains open and I think that creates confusion I would rather suggest that we close the form .

### New Dependency

react-toastify  

Fixes #117 

### Type of Change:
- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
![Peek 2021-03-09 17-51](https://user-images.githubusercontent.com/56596436/110479510-7e636a80-810b-11eb-879b-f52adf0ae3a2.gif)
![Peek 2021-03-09 17-53](https://user-images.githubusercontent.com/56596436/110479514-7f949780-810b-11eb-841f-e290b3ba1ae0.gif)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

2021-03-09 13:48 UTC, ruddi10 commented
@codesankalp  @keshakaneria @Aaishpra  kindly review it

2021-03-09 16:58 UTC, keshakaneria requested changes
Great! Replace the green color with a bit of dark shade and **black** text written in ALL CAPS with added exclamation mark for Success, so that it is visible. Same goes for the red shade for unsuccessful.
You can use the following shades:
- Green: #4BE043
- Red: #F61E1E

2021-03-09 17:03 UTC, ruddi10 commented
@keshakaneria sure will implement those any other suggestions except for that.

2021-03-09 17:11 UTC, keshakaneria commented
> @keshakaneria sure will implement those any other suggestions except for that.

Otherwise looks good 👍

2021-03-09 19:30 UTC, codesankalp requested changes
See my review comments @ruddi10.

2021-03-09 19:30 UTC, codesankalp commented on package.json
> +    "react-toastify": "^7.0.3",
I am not sure about adding this, but it looks good. @Aaishpra and @keshakaneria  What do you think about adding this?
(I am asking this because it is mentioned to use semantic-UI.)

2021-03-09 19:30 UTC, codesankalp commented on src/actions/info.js
> +import axios from "axios";
Why this file has been changed @ruddi10 as there is no need for change in actions.
If it's just re-formatting then unstage this file.

2021-03-09 19:30 UTC, codesankalp commented on src/components/App.js
> -import React, { Component } from 'react'
Again, If there is no change added by you in the code of this file then unstage that file because there is a PR for this.

2021-03-09 19:30 UTC, codesankalp commented on src/components/Dashboard.js
> -import React, { Component } from 'react'
Also, unstage this file if there is no change made by you.

2021-03-20 14:01 UTC, codesankalp commented
@ruddi10 Please resolve the merge conflicts and do the suggested changes.

2021-04-12 11:10 UTC, codesankalp commented
Closing this PR due to inactivity and no response from @ruddi10

2021-04-12 12:08 UTC, ruddi10 commented
@codesankalp I will complete this by this weekend if that's not a problem?

2021-04-12 12:28 UTC, codesankalp commented
Ok, @ruddi10 reopening this pull request :+1:

2021-04-22 19:01 UTC, codesankalp commented
@ruddi10 Any updates?

2021-04-23 09:36 UTC, ruddi10 commented
> @ruddi10 Any updates?

@codesankalp some serious health issues in family will it be fine if I take some time?

2021-04-23 10:03 UTC, codesankalp commented
> > @ruddi10 Any updates?
> 
> @codesankalp some serious health issues in family will it be fine if I take some time?

Ok, @ruddi10 take the time but keep updating in a few days.

2021-07-22 16:18 UTC, codesankalp commented
@ruddi10 Can you please update your progress? I will wait for 2 days for your reply and after that I will close this PR.

2021-10-02 10:52 UTC, isabelcosta commented
> @codesankalp some serious health issues in family will it be fine if I take some time?

@ruddi10 I will close this due to lack of response. I hope you and your family are well now 🙏🏾 
If you wish to work on this again in the future, feel free to claim the issue again and we'll assign this to you.

cc @codesankalp

2021-10-02 10:52 UTC, closed without merging