Change links and text to the current repository name
anitab-org/open-source-programs-web pull request #121
Opened 2021-03-10 19:42 UTC by The-Keshav-Agarwal

### Description

I changed all the texts and link which includes `open-source-programs-web` and `open-source-programs-backend ` to `anitab-forms-web` and `anitab-forms-backend` respectively.

Fixes #120 

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

2021-03-11 13:15 UTC, keshakaneria requested changes
The following places still needs to be updated:
- `docs/README.md`
- Check all `*.js` files which currently aren't edited. We will have to replace them too even if the files aren't seen to users, so that in future there is no confusion of names.

2021-03-11 17:53 UTC, The-Keshav-Agarwal commented
@keshakaneria I made the changes please review it again.

2021-03-11 18:30 UTC, keshakaneria requested changes
You missed [this](https://github.com/anitab-org/anitab-forms-web/blob/develop/docs/src/pages/index.js#L15).

2021-03-11 18:42 UTC, The-Keshav-Agarwal commented
@keshakaneria should i need to change all `open source programs (osp)` text to `anitab forms program`?

2021-03-11 18:47 UTC, keshakaneria commented
> @keshakaneria should i need to change all `open source programs (osp)` text to `anitab forms program` also? because till now i changed only `open-source-programs-web` and `open-source-programs-backend`.

Oops! My fault, the issue doesn't include this so the changes made are fine 😄

2021-03-11 19:37 UTC, keshakaneria approved these changes, later dismissed
You are good to go! 🎉😄

2021-03-12 12:27 UTC, ashwinijha6 requested changes

2021-03-12 12:27 UTC, ashwinijha6 commented on .github/CONTRIBUTING.md
>  -   You can join us on [AnitaB.org Open Source Zulip](https://anitab-org.zulipchat.com/). Each active repo has its own stream to direct questions to (for example #powerup or #portal). Open Source Pro
@The-Keshav-Agarwal  just change the the link & the name here also for zulip
Link : https://anitab-org.zulipchat.com/#narrow/stream/237907-anitab-forms
Name of the Stream : [#anitab-forms]

2021-03-12 12:30 UTC, ashwinijha6 reviewed
Hey @The-Keshav-Agarwal are you changing the repo name inside the docs/ also for docusaurus 
because it will require you to install `docusaurus`,  `yarn` & `npm` & then publish it on `surge` ?

2021-03-12 13:57 UTC, The-Keshav-Agarwal commented
@ashwinijha6 I am changing name in docs folder and in .js file.

2021-03-12 17:21 UTC, ashwinijha6 requested changes
@The-Keshav-Agarwal I was just asking because as there are a lot of files in docs/docs where the repo name needs to be changed like:
- Home.md under Home & in the About the Section (2)
- User Interface Design under that change OSP
- Main Base Concepts.md here also it says OSP Application (should this be changed @keshakaneria )
- Future Ideas.md the zulip stream
-  You will need to change the description in index.js

2021-03-12 17:21 UTC, ashwinijha6 commented on README.md
>  # Open Source Programs (Frontend)
Change the name here to `Anitab Forms Web`

2021-03-12 17:21 UTC, ashwinijha6 commented on README.md
>  [![project chat](https://img.shields.io/badge/zulip-join_chat-brightgreen.svg)](https://anitab-org.zulipchat.com/#narrow/stream/237907-open-source-progs)
The zulip stream link needs to changed here

2021-03-12 17:21 UTC, ashwinijha6 commented on docs/README.md
> +Surge is a static web hosting platform. It is used to deploy our spen source programs docusaurus from the command line in a minute.
change it to `spen` to `open`

2021-03-12 17:21 UTC, ashwinijha6 commented on docs/docs/2020-Bismita-Guha.md
> +I plan to work on the backend and frontend of Open Source Programs in this GSoC period. My mentors are [Maybelline Burgos](https://github.com/mayburgos), [Monal Shadi](https://github.com/Monal5031),
here also the repo name needs to changed in the first line. What do you think @keshakaneria?
I'm not sure about this as during GSoc'20 the name was `Open Source Programs`

2021-03-12 17:21 UTC, ashwinijha6 commented on docs/docs/Fork,-Clone,-Remote-and-Pull-Request.md
>  ![Forking](https://user-images.githubusercontent.com/43119923/81509477-99692080-9328-11ea-89e2-6e54f04b9544.jpg)
Change the screenshot here for fork

2021-03-12 17:21 UTC, ashwinijha6 commented on docs/docs/Getting-Started.md
>  - You can join the [#open-source-progs](https://anitab-org.zulipchat.com/#narrow/stream/237907-open-source-progs) channel on AnitaB.org Open Source Zulip, to see or participate in the project's discu
change the zulip stream link here

2021-03-12 17:24 UTC, ashwinijha6 commented
Check with the conflicts

2021-03-20 14:00 UTC, codesankalp commented
@The-Keshav-Agarwal Please do the suggested changes.

2021-04-03 02:17 UTC, Aaishpra commented
@The-Keshav-Agarwal please update the PR as requested and remove the merge conflicts or this PR will be closed and issue will be made available again.

2021-04-03 05:48 UTC, The-Keshav-Agarwal commented
@Aaishpra I am closing this PR. please assign this issue to someone else.

2021-04-03 05:48 UTC, closed without merging