docs: migrate docusaurus deployment from surge to github pages
anitab-org/open-source-programs-web pull request #137
Opened 2021-04-30 09:52 UTC by Harshita-Kanal

### Description

Migrate docusaurus deployment from surge to github pages.

Fixes #126 

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] Any dependent changes have been published in downstream modules

2021-05-03 17:25 UTC, codesankalp requested changes

2021-05-03 17:25 UTC, codesankalp commented on .github/workflows/docs.yml
> +          npm run deploy
add a new line at the end of file.

2021-05-03 17:25 UTC, codesankalp commented on README.md
> +Documentation for the project is hosted [here](https://anitab-org.github.io/open-source-programs/). We use `Docusaurus` for maintaining the documentation of the project.
Please use anitab-forms-web

2021-05-04 04:36 UTC, Aaishpra commented on docs/docusaurus.config.js
> +  baseUrl: '/open-source-programs/',
```suggestion
  baseUrl: '/anitab-forms-web/',
```

2021-05-04 13:49 UTC, Harshita-Kanal commented
Added the changes

2021-05-05 14:59 UTC, Aaishpra submitted a review, later dismissed
LGTM 💯

2021-05-14 18:57 UTC, Amulya-coder submitted a review, later dismissed
Looks good @Harshita-Kanal, could you please fix the conflicts.

2021-05-15 18:58 UTC, Harshita-Kanal commented
Fixed the conflict

2021-05-15 19:19 UTC, Amulya-coder approved these changes

2021-08-14 20:31 UTC, vj-codes approved these changes
LGTM 🎉

2021-08-14 20:31 UTC, vj-codes commented
@Aaishpra can you review this again please?

2021-08-16 05:15 UTC, Aaishpra approved these changes
Great work here 👍

2021-10-01 19:41 UTC, isabelcosta approved these changes
Great work @Harshita-Kanal 🙌🏾  Thank you for contributing!

2021-10-01 19:45 UTC, isabelcosta commented
I just set this the GH_PAGES_DEPLOY key, I hope it works now 🙏🏾

2021-10-01 19:45 UTC, merged