Add medium link to Docusaurs page footer
anitab-org/open-source-programs-web pull request #172
Opened 2021-10-08 20:36 UTC by ToluAkin

### Description

- Add medium link to Docusaurs page footer

Fixes #171

### Type of Change:
- Add data object to the file `docusaurus.config.js`

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Run the code

### Checklist:
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2021-10-08 20:37 UTC, ToluAkin commented
@isabelcosta

2021-10-08 20:50 UTC, codesankalp commented
@ToluAkin Please update the PR description also.

2021-10-08 20:51 UTC, isabelcosta commented
@ToluAkin I will review ;) Just as FYI, I changed your issue description to have the link to the issue you are solving. Usually, you have to add like `Fixes #123` where 123 is the number of the issue. In this way, once this is merged GitHub will close the issue automatically.

2021-10-08 20:51 UTC, codesankalp requested changes

2021-10-08 20:51 UTC, codesankalp commented on docs/docusaurus.config.js
>                href: 'https://medium.com/anitab-org-open-source',
I think both are the same, so remove one.

2021-10-08 20:52 UTC, isabelcosta commented on docs/docusaurus.config.js
>                href: 'https://medium.com/anitab-org-open-source',
Good point! I only noticed that now. thank you @codesankalp 🙌🏾

2021-10-08 20:54 UTC, isabelcosta requested changes
Thank you for contributing. Once you address my comment and @codesankalp 's comment I am happy to approve :)

2021-10-08 20:54 UTC, isabelcosta commented on docs/docusaurus.config.js
> +            },
you can remove this too :) Having it under `Zulip` on the `Community` column is enough :)

2021-10-08 21:08 UTC, isabelcosta submitted a review, later dismissed
Thank you so much for your contribution @ToluAkin ! This looks great!

2021-10-08 22:14 UTC, ToluAkin commented
@isabelcosta All checks are passing now. Is the PR title okay? Do I need to remove the phrase after the issue number?

2021-10-08 22:14 UTC, isabelcosta approved these changes
Thank you for fixing the failing check! Even though you did not need it 🤗 
I'll approve! Thank you for contributing @ToluAkin !

2021-10-08 22:15 UTC, isabelcosta commented
@ToluAkin the PR title looks good. I wouldn't add the "Fixes #171" part, since it is already in the issue description. But its fine, as long as the title also indicates what the PR is actually fixing :) So it looks great to me!

2021-10-08 22:27 UTC, ToluAkin commented
> @ToluAkin the PR title looks good. I wouldn't add the "Fixes #171" part, since it is already in the issue description. But its fine, as long as the title also indicates what the PR is actually fixing :) So it looks great to me!

Thank you!

2021-10-09 12:35 UTC, ToluAkin commented
Hi @codesankalp , @vj-codes Could you help me check this again if it is good to go? Thanks.

2021-10-09 13:34 UTC, Aaishpra approved these changes
Great work Thanks for contributing @ToluAkin

2021-10-09 13:35 UTC, Aaishpra commented
I have also added the Hacktoberfest label here.

2021-10-09 14:00 UTC, ToluAkin commented
> I have also added the Hacktoberfest label here.

😃 ..... Thank you! I'm happy to help.

2021-10-09 15:21 UTC, vj-codes approved these changes
LGTM 🎉

2021-10-09 15:32 UTC, isabelcosta commented
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

   * _Run docusaurus website and see footer_  
     _Screenshot/gif_:  ![image](https://user-images.githubusercontent.com/11148726/136664768-d96b29aa-d5fc-48a1-a278-23576927784c.png)
     _Expected Result_:  Medium publication link should appear in the footer of Docusaurus
     _Actual Result_: as expected there is a medium link in the community tab
  
3. Additional Comments: steps to run this (also following [our QA guide](https://github.com/anitab-org/documentation/blob/master/quality-assurance.md))
    ```
    cd docs
    yarn install
    yarn start
    go to http://localhost:3000/anitab-forms-web/
    ```
4. Status of PR Changed to: Ready to Merge.

2021-10-09 15:33 UTC, isabelcosta commented
@ToluAkin I would suggest you to in the "How Has This Been Tested?" next time to show a screenshot showing you tested the change. That makes for a good pull request description that can help maintainers look for your change :)

2021-10-09 15:34 UTC, merged