Tests: Add tests for checking validations on Register form
anitab-org/open-source-programs-web pull request #175
Opened 2021-10-10 22:00 UTC by jennypoon

### Description

Add tests to check input validations and button ui on Register form

Fixes #173 
- Note: if the email or username field is empty, the button is disabled so no validation UI can be provided if the user cannot press the Register button. I added 3 tests to show that the button is disabled if those fields are empty, as well as a test to show it's enabled when all fields are filled. 

### Type of Change:
- Code: Added `data-testid` to input and button components
- Quality Assurance: Added testing for Register Component

### How Has This Been Tested?
Run `npm test` on the CLI - all tests should pass

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

2021-10-11 02:56 UTC, codesankalp requested changes
@jennypoon Great work :+1: 
There are few tests which I think can be added:
1. Mock the Axios and test for the condition where a username is already registered.
2. Successful Registration message check.
3. On toggling the Password eye icon it should show or hide the password.

2021-10-11 02:56 UTC, codesankalp commented on src/tests/Register.test.js
> +  it('Should be disabled if username field is empty', () => {
This test can be merged with the next test case.

2021-10-14 04:49 UTC, jennypoon commented
> @jennypoon Great work 👍 There are few tests which I think can be added:
> 
> 1. Mock the Axios and test for the condition where a username is already registered.
> 2. Successful Registration message check.
> 3. On toggling the Password eye icon it should show or hide the password.

I'm pretty new to testing. Could you provide some guidance on how I can mock the `postRegister` axios request and then check to see if there's a success message on the Register component?

2021-10-14 05:04 UTC, codesankalp commented
> > @jennypoon Great work +1 There are few tests which I think can be added:
> > 
> > 1. Mock the Axios and test for the condition where a username is already registered.
> > 2. Successful Registration message check.
> > 3. On toggling the Password eye icon it should show or hide the password.
> 
> I'm pretty new to testing. Could you provide some guidance on how I can mock the `postRegister` axios request and then check to see if there's a success message on the Register component?

@jennypoon You can mock the Axios request, see this for reference: https://jestjs.io/docs/mock-functions#mocking-modules
after this, all the other things are the same i.e. mock the implementation of Axios, submit the form, and expect that a successful response is being returned.

2021-10-15 06:45 UTC, codesankalp requested changes
@jennypoon Please make the last change :point_down:

2021-10-15 06:45 UTC, codesankalp commented on src/tests/Register.test.js
> +});
@jennypoon You can change this test to this (I have tested it):

```suggestion
describe('Successful Registration', () => {
  it('Should see success message', async () => {
    const response = {
      data: { detail: 'Please confirm your email to Login succesfully' },
      status: 200,
    };

    axios.post.mockImplementationOnce(() => Promise.resolve(response));

    const callback = jest.fn();
    const dispatchMock = jest.fn();
    const registration = {
      username: 'username123',
      email: 'test@gmail.com',
      password: 'Testpassword123!',
      confirm_password: 'Testpassword123!',
    };

    const dispatch = postRegister(registration, callback);
    await dispatch(dispatchMock);
    expect(callback).toHaveBeenCalled();
    expect(dispatchMock).toHaveBeenCalledWith({
      payload: response.data,
      type: 'REGISTER',
    });
  });
});
```

2021-10-16 05:36 UTC, jennypoon commented
PR have been added to include the suggested tests.

2021-10-16 09:24 UTC, codesankalp approved these changes
Thanks @jennypoon :+1:

2021-10-16 14:31 UTC, Aaishpra approved these changes
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done 

2. All possible responses (positive and negative tests) were tested as below:

- Ran ```npm test```
![image](https://user-images.githubusercontent.com/66299533/137591373-6580c035-e5ff-42b2-872b-670a3981c54c.png)

   

4. Additional Comments:  The tests are working as expected. 

5. Status of PR Changed to: Ready to Merge.

2021-10-17 13:33 UTC, isabelcosta commented
@Aaishpra thank you for testing this 🙏🏾 really really appreciate it

2021-10-17 13:35 UTC, merged

2021-10-17 13:36 UTC, isabelcosta commented
Great work @jennypoon 👏🏾 🙌🏾