test: validation tests for login component
anitab-org/open-source-programs-web pull request #179
Opened 2021-10-12 15:16 UTC by groopav

### Description

Fixes #174

### Type of Change:

- Quality Assurance: Added tests for Login component

### How Has This Been Tested?

I ran npm test and noted that both existing and new tests passed. 
![image](https://user-images.githubusercontent.com/61742380/136982835-7aa1bf56-5fd9-4d27-b593-c5a374b63611.png)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

2021-10-13 06:15 UTC, Aaishpra reviewed
Thanks for finishing this quick, @random3900 I have made some comments please have a look

2021-10-13 06:15 UTC, Aaishpra commented on src/tests/Login.test.js
> +  fireEvent.change(screen.getByPlaceholderText('Enter your password...'), {
Hi @random3900 to maintain consistency in code can you get data from login form by creating a data-testid instead of getting it by placeholder and other values
Something like 
  ```
data-testid="hide-password" 

firevent.change(screen.getByTestId('hide-password'))
````

2021-10-13 15:35 UTC, groopav commented on src/tests/Login.test.js
> +  fireEvent.change(screen.getByPlaceholderText('Enter your password...'), {
Thanks for your feedback, I've made the necessary changes.

2021-10-15 14:19 UTC, groopav commented on src/tests/Login.test.js
> +  fireEvent.change(screen.getByPlaceholderText('Enter your password...'), {
Hey @Aaishpra please let me know if I need to modify anything else, thanks!

2021-10-15 14:46 UTC, codesankalp requested changes
@random3900 Please see my comments.
For mocking axios, see this as reference: https://github.com/anitab-org/anitab-forms-web/pull/175#discussion_r729558779

2021-10-15 14:46 UTC, codesankalp commented on src/tests/Login.test.js
> +  expect(loginButton).toBeEnabled();
This test doesn't match with test description. It is just enabling the login button.
I would suggest to mock Axios and write a test case for successful login.

2021-10-15 18:56 UTC, groopav commented on src/tests/Login.test.js
> +  expect(loginButton).toBeEnabled();
Thanks for your feedback, I've added the test case. Please let me know if anything else needs to be modified.

2021-10-16 09:26 UTC, codesankalp approved these changes
Thanks @random3900 :+1:

2021-10-16 14:17 UTC, Aaishpra approved these changes
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done 

2. All possible responses (positive and negative tests) were tested as below:

- Ran ```npm test```
![image](https://user-images.githubusercontent.com/66299533/137590928-33503aa7-cd40-4000-bfae-d8a8034c504f.png)

   

4. Additional Comments:  The tests are working as expected. 

5. Status of PR Changed to: Ready to Merge.

2021-10-16 14:20 UTC, Aaishpra commented
Thanks for  your contributions @random3900 .
@isabelcosta can you run the workflow.

2021-10-16 14:23 UTC, random3900 commented
Thank you @Aaishpra @codesankalp :D

2021-10-17 13:36 UTC, merged