Updated Zulip.js
anitab-org/open-source-programs-web pull request #180
Opened 2021-10-15 05:23 UTC by msaini28r

### Description

Fixes #72

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

2021-10-15 05:23 UTC, msaini28r commented
The issue is solved. #72

2021-10-15 06:17 UTC, codesankalp requested changes
See my comments @msaini0r :point_down:

2021-10-15 06:17 UTC, codesankalp commented on src/components/Zulip.js
> -                        {zulipstat[0] ? zulipstat[0].newcomers_messages : 0}
Why are you removing this?
You need to change the condition so that it can render without any errors.
```javascript
{zulipstat && zulipstat[0] && zulipstat[0].newcomers_message ? zulipstat[0].newcomers_message : 0}
```

Same change for other lines also.

2021-10-15 06:52 UTC, msaini28r commented on src/components/Zulip.js
> -                        {zulipstat[0] ? zulipstat[0].newcomers_messages : 0}
@codesankalp can you please check if I made the right changes?

2021-10-15 07:11 UTC, codesankalp requested changes

2021-10-15 07:11 UTC, codesankalp commented on src/components/Zulip.js
> -import { connect } from 'react-redux';
@msaini0r You have removed the whole code from this file. Please revert it.

2021-10-15 07:24 UTC, msaini28r commented on src/components/Zulip.js
> -import { connect } from 'react-redux';
@can you give me instructions how to revert it. @codesankalp

2021-10-15 07:41 UTC, msaini28r commented on src/components/Zulip.js
> -import { connect } from 'react-redux';
@codesankalp should i delete that branch?

2021-10-16 09:29 UTC, codesankalp commented on src/components/Zulip.js
> +                        {zulipstat && zulipstat[0] && zulipstat[0].newcomers_message ? zulipstat[0].newcomers_message : 0}
This line looks repeated for `zulipstat && zulipstat[0]`. Can you please remove this `zulipstat && zulipstat[0]` from each line and add `zulipstat && zulipstat[0]` in parent tag (`ul`)?
```suggestion
                        {zulipstat[0].newcomers_message ? zulipstat[0].newcomers_message : 0}
```

2021-10-16 09:39 UTC, msaini28r commented on src/components/Zulip.js
> +                        {zulipstat && zulipstat[0] && zulipstat[0].newcomers_message ? zulipstat[0].newcomers_message : 0}
@codesankalp check now changes done.

2021-10-16 09:57 UTC, codesankalp commented on src/components/Zulip.js
> +                    <zulipstat && zulipstat[0]>
```suggestion
                    {zulipstat && zulipstat[0] ? <ul>below code<ul> : null}
```

2021-10-16 10:31 UTC, msaini28r reviewed
@codesankalp see!!

2021-10-16 11:04 UTC, codesankalp approved these changes

2021-10-16 13:53 UTC, Aaishpra approved these changes

2021-10-17 12:52 UTC, isabelcosta commented
@msaini0r please edit the pull request description with a description of the changes and how you tested this? This is a good practice for future PRs, whether it's in our community or other projects, and good for documentation purposes 🤗

2021-10-17 12:55 UTC, isabelcosta requested changes
@msaini0r could you please check why the PR check is failing? This seems to be related to your PR. Once you fix the failing check I can approve this PR and merge it.

2021-10-17 20:36 UTC, isabelcosta commented
removed Ready to Merge label as the PR checks are failing cc @Aaishpra

2021-10-18 07:07 UTC, msaini28r commented
@isabelcosta I am not able to find the issue. I would like to worrk on some other issues

2021-10-18 07:15 UTC, Aaishpra commented
> @isabelcosta I am not able to find the issue. I would like to worrk on some other issues

Hi @msaini0r only linters and formatters check is failing if you can fix them it would be great
Try running npm run lint to fix them
Pasting the error log here so you can have a look.
```
 
Linters and Formatters
failed 18 hours ago in 58s
Search logs
3s
1s
3s
47s
4s
Run npm run lint

> osp@0.1.0 lint /home/runner/work/anitab-forms-web/anitab-forms-web
> eslint .


/home/runner/work/anitab-forms-web/anitab-forms-web/src/components/Zulip.js
Error:   61:50  error  Insert `(⏎······················`                                                                                                                                                                                                                                             prettier/prettier
Error:   62:23  error  Insert `··`                                                                                                                                                                                                                                                                   prettier/prettier
Error:   63:1   error  Insert `··`                                                                                                                                                                                                                                                                   prettier/prettier
Error:   64:25  error  Replace `{zulipstat[0].newcomers_message·?·zulipstat[0].newcomers_message` with `··{zulipstat[0].newcomers_message⏎····························?·zulipstat[0].newcomers_message⏎···························`                                                                  prettier/prettier
Error:   65:1   error  Insert `··`                                                                                                                                                                                                                                                                   prettier/prettier
Error:   66:23  error  Insert `··`                                                                                                                                                                                                                                                                   prettier/prettier
Error:   67:1   error  Insert `··`                                                                                                                                                                                                                                                                   prettier/prettier
Error:   68:1   error  Replace `························{zulipstat[0].celebrate_message·?·zulipstat[0].celebrate_message` with `··························{zulipstat[0].celebrate_message⏎····························?·zulipstat[0].celebrate_message⏎···························`                  prettier/prettier
Error:   69:1   error  Replace `······················` with `························`                                                                                                                                                                                                              prettier/prettier
Error:   70:1   error  Insert `··`                                                                                                                                                                                                                                                                   prettier/prettier
Error:   71:25  error  Insert `··`                                                                                                                                                                                                                                                                   prettier/prettier
Error:   72:1   error  Replace `························{zulipstat[0].opportunities_message·?·zulipstat[0].opportunities_message` with `··························{zulipstat[0].opportunities_message⏎····························?·zulipstat[0].opportunities_message⏎···························`  prettier/prettier
Error:   73:1   error  Insert `··`                                                                                                                                                                                                                                                                   prettier/prettier
Error:   74:23  error  Insert `··`                                                                                                                                                                                                                                                                   prettier/prettier
Error:   75:1   error  Insert `··`                                                                                                                                                                                                                                                                   prettier/prettier
Error:   76:25  error  Replace `{zulipstat[0].questions_message·?·zulipstat[0].questions_message` with `··{zulipstat[0].questions_message⏎····························?·zulipstat[0].questions_message⏎···························`                                                                  prettier/prettier
Error:   77:1   error  Insert `··`                                                                                                                                                                                                                                                                   prettier/prettier
Error:   78:23  error  Insert `··`                                                                                                                                                                                                                                                                   prettier/prettier
Error:   79:1   error  Replace `························` with `··························`                                                                                                                                                                                                          prettier/prettier
Error:   80:1   error  Replace `·······················{zulipstat[0].general_message·?·zulipstat[0].general_message` with `··························{zulipstat[0].general_message⏎····························?·zulipstat[0].general_message⏎···························`                           prettier/prettier
Error:   81:1   error  Insert `··`                                                                                                                                                                                                                                                                   prettier/prettier
Error:   82:1   error  Replace `····················</ul>` with `······················</ul>⏎····················)`                                                                                                                                                                                  prettier/prettier`
```

2021-10-18 07:45 UTC, msaini28r commented
@Aaishpra already tried npm run lint but it is showing me an error.

2021-10-19 16:48 UTC, closed without merging