Close published form to stop responses
anitab-org/open-source-programs-web pull request #41
Opened 2020-07-13 14:21 UTC by bismitaguha

### Description

- Added a button to close a published form
- Only admins can perform the function

Fixes #13 

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

N/A

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] Any dependent changes have been published in downstream modules

2020-07-13 14:22 UTC, bismitaguha commented
Only the last commit is relevant to this PR.
@sidvenu @abha224

2020-07-13 16:22 UTC, sidvenu requested changes
As said in the OSP weekly meeting, please add a message saying "The form is no longer accepting responses" if the form is closed, rather than displaying "Form not found" in all cases.

2020-07-20 14:21 UTC, abha224 commented on src/components/PublishedForm.js
> +            published_status: 'unpublished'
@bismitaguha You have used the publish_status variable to denote unpublished, published and closed. Can you use a different variable for denoting status= closed? something like form_status?

2020-07-23 16:22 UTC, abha224 commented
@bismitaguha Pls add a screenshot/gif whenever you make a pr. Its easier to understand the change that way.

2020-07-25 15:22 UTC, bismitaguha commented on src/components/PublishedForm.js
> +            published_status: 'unpublished'
This is the variable present in the backend also, I cannot change it.

2020-07-28 03:57 UTC, sidvenu commented on src/components/PublishedForm.js
> +            published_status: 'unpublished'
@abha224 I believe having an enum of the 3 statuses (i.e., whatever changes Bismita has made) would make more sense than having true or false for two separate parameters.

2020-08-01 20:43 UTC, abha224 approved these changes

2020-08-01 20:43 UTC, sidvenu approved these changes

2020-08-01 20:44 UTC, merged