[WIP]: Add scripts for file upload
anitab-org/open-source-programs-web pull request #42
Opened 2020-07-16 21:58 UTC by bismitaguha

### Description

Fixes #11 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

N/A

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] Any dependent changes have been published in downstream modules

2020-07-16 21:59 UTC, bismitaguha commented
@abha224 @sidvenu I am having doubts regarding the URL of upload. So I needed help there

2020-07-20 09:57 UTC, sidvenu commented
@bismitaguha could you comment the doubts here?

2020-07-20 09:58 UTC, sidvenu submitted a review, later dismissed
Looks good till the work done.

2020-07-20 14:23 UTC, abha224 commented
@bismitaguha Is the issue resolved?

2020-07-20 14:31 UTC, bismitaguha commented
@abha224 @sidvenu the URL is throwing errors.

2020-07-21 15:37 UTC, abha224 commented
@bismitaguha can you add a screenshot of the error for reference?

2020-07-21 17:58 UTC, bismitaguha commented
URL error
![Screenshot from 2020-07-21 23-27-15](https://user-images.githubusercontent.com/43119923/88089542-cd26b900-cba9-11ea-893e-6f587ad691b1.png)

2020-07-23 16:48 UTC, sidvenu commented
This sounds like you're appending a JS object to a string. Try running the following in your browser console:

```
const obj = {
    name: "John Smith",
    email: "johnsmith@nomail.com"
};
const urlPath = '/' + obj
urlPath
```
This will print `/[object Object]`.

Can you recheck your code for a similar pattern?

2020-08-03 15:02 UTC, bismitaguha commented
![Screenshot from 2020-08-03 20-27-25](https://user-images.githubusercontent.com/43119923/89196557-0149a300-d5c8-11ea-8d7a-fe386c39a131.png)
I am constantly receiving this error and have tried modifying the `.env` file also based on these sources [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html) & [github issue](https://github.com/aws/aws-cli/issues/1037).
If @sidvenu and @abha224 you could look into this and help me out here. I have referred to [this blog](https://medium.com/@only4/upload-files-to-s3-buckets-from-react-45aaaa651e28) while writing the code.

2020-08-03 17:42 UTC, sidvenu commented
Update: Bismita and I discussed this in our 1:1, and we found that this is a problem caused by the `.env` file not getting loaded. @bismitaguha is working to solve that.

2020-08-03 19:20 UTC, bismitaguha commented
Update: The env problem is solved. Now I am receiving a different error
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.

I am working on this, meanwhile if anyone finds any resource please send a link. @sidvenu @abha224

2020-08-03 19:50 UTC, bismitaguha commented
The complete config:
![Screenshot from 2020-08-04 01-19-45](https://user-images.githubusercontent.com/43119923/89221275-a1b3bd80-d5f0-11ea-9ebd-ccd86d2c5506.png)

2020-08-05 20:00 UTC, bismitaguha commented
@sidvenu @abha224 All issues are resolved please review!!!!

2020-08-06 16:57 UTC, sidvenu requested changes

2020-08-06 16:57 UTC, sidvenu commented on src/components/Upload.js
> +// import { postUpload } from '../actions/upload'
If not necessary, remove.

2020-08-06 16:57 UTC, sidvenu commented on src/components/Upload.js
> +        super(props)
A code comment here would be appropriate.

2020-08-06 16:57 UTC, sidvenu commented on src/urls.js
> +export function file() {
```suggestion
export function urlFileUpload() {
```

2020-08-06 16:57 UTC, sidvenu commented on src/urls.js
> +export function file() {
Rename the references to this function too.

2020-08-08 15:19 UTC, bismitaguha commented
@sidvenu this is the sample script which will be reused in a separate component in the form responses. So this part will get deleted there completely.

2020-08-09 16:31 UTC, sidvenu commented
@bismitaguha In that case, you can copy and paste the comment as well. I feel an individual contributor should be able to understand this repo's code at all points in history, and thus comments are important no matter how redundant it would be in the future. @abha224 what do you think?

2020-08-15 18:25 UTC, abha224 approved these changes
Reviewed and tested. PR looks good to me :+1:

2020-08-15 18:57 UTC, sidvenu approved these changes
LGTM!

2020-08-15 19:00 UTC, merged