View form
anitab-org/open-source-programs-web pull request #43
Opened 2020-07-18 21:12 UTC by bismitaguha

### Description

Fixes #12 

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

Manual
![Screenshot from 2020-07-19 02-34-47](https://user-images.githubusercontent.com/43119923/87862026-58653c00-c969-11ea-8332-907f4464910b.png)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been published in downstream modules

2020-07-18 21:12 UTC, bismitaguha commented
@sidvenu @abha224 only the last [commit](https://github.com/anitab-org/open-source-programs-web/pull/43/commits/5f100719de05e05f0731c9be26f1395bb6b807c1) is relevant to this PR.

2020-07-20 09:54 UTC, sidvenu requested changes

2020-07-20 09:54 UTC, sidvenu commented on src/components/Questions.js
> +        console.log(form)
To be removed?

2020-07-28 03:59 UTC, sidvenu submitted a review, later dismissed
LGTM.

2020-08-12 02:42 UTC, sidvenu commented
@bismitaguha may I know the updates on this PR?

2020-08-15 16:30 UTC, bismitaguha commented
@sidvenu I had updated this PR in the beginning of last week only. Please review!

2020-08-15 17:00 UTC, sidvenu requested changes

2020-08-15 17:00 UTC, sidvenu commented on src/components/Questions.js
> +                    :
This nested ternary operator needs to be refactored for better readability. If that isn't possible - add a comment.

2020-08-15 17:30 UTC, sidvenu approved these changes
LGTM!

2020-08-15 17:33 UTC, abha224 approved these changes
This pr is reviewed and tested. The code is working as expected :+1:

2020-08-15 17:35 UTC, merged