feat: Modify close and republish functions and reducers
anitab-org/open-source-programs-web pull request #53
Opened 2020-08-15 18:27 UTC by bismitaguha

### Description

Fixes #52 

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Manual testing

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] Any dependent changes have been published in downstream modules

2020-08-15 19:32 UTC, sidvenu requested changes
@bismitaguha is this PR complete? Can you attach a GIF?

2020-08-15 19:32 UTC, sidvenu commented on q
> +[33mcommit 0e2a36e664ec5c66e32ecf5a80ff153e6eef9b04[m[33m ([m[1;36mHEAD -> [m[1;32mview-form[m[33m)[m
Should be removed?

2020-08-24 16:29 UTC, sidvenu approved these changes, later dismissed
LGTM. @bismitaguha can you attach a GIT here?

2020-08-25 16:29 UTC, bismitaguha commented
@sidvenu @abha224 I showed this in the demo. Please merge this PR.

2020-08-27 09:54 UTC, bismitaguha commented
@abha224 Modified the errors!!!
![Screenshot from 2020-08-27 15-21-55](https://user-images.githubusercontent.com/43119923/91425889-5e5c1000-e879-11ea-93fe-3b5e4edbed5e.png)

2020-08-28 04:39 UTC, sidvenu requested changes

2020-08-28 04:39 UTC, sidvenu commented on src/components/PublishedForm.js
> +        console.log(this.state)
To be removed

2020-08-28 11:40 UTC, sidvenu approved these changes

2020-08-28 13:24 UTC, abha224 approved these changes
Reviewed and tested. :+1:

2020-08-28 13:30 UTC, merged