Add feature for viewing submissions and searching by name and form name
anitab-org/open-source-programs-web pull request #54
Opened 2020-08-17 14:52 UTC by bismitaguha

### Description

- Added list view of submissions
- Added feature for search by form name and user name

Fixes #49 

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

![Screenshot from 2020-08-17 20-19-37](https://user-images.githubusercontent.com/43119923/90409787-3d502e00-e0c7-11ea-9f9f-20c1702f4db2.png)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented on my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] Any dependent changes have been published in downstream modules

2020-08-17 14:53 UTC, bismitaguha commented
CSS work left!

2020-08-21 12:12 UTC, sidvenu requested changes
LGTM till now - just remove the test log. Is this PR WIP?

2020-08-21 12:12 UTC, sidvenu commented on src/components/Submission.js
> +        console.log(this.state)
```suggestion
```

2020-08-27 07:48 UTC, sidvenu commented
Is this PR WIP or done? If done, please request a review. If not, please add 'WIP' to the title.

2020-08-28 11:39 UTC, sidvenu approved these changes

2020-08-28 11:58 UTC, bismitaguha commented
@abha224 @sidvenu This PR will require changes after the merge of the submissions PR. Please do not merge before that!!!

2021-02-14 10:23 UTC, isabelcosta commented
Will close due to inactivity, and make the issue available again.
Thank you for starting this work @abha224

2021-02-14 10:23 UTC, closed without merging